import { mkdirSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { homedir } from 'node:os';
import { getClaudeConfigDir } from '../../findcc.js';

export const KEEP_CLAUDE_NO_FLICKER_ENV = 'CCV_KEEP_CLAUDE_CODE_NO_FLICKER';

function shouldKeepClaudeNoFlicker(env = {}, sourceEnv = process.env) {
  return env[KEEP_CLAUDE_NO_FLICKER_ENV] === '1' || sourceEnv?.[KEEP_CLAUDE_NO_FLICKER_ENV] === '1';
}

export function stripClaudeNoFlickerUnlessOptedIn(env, sourceEnv = process.env) {
  if (!shouldKeepClaudeNoFlicker(env, sourceEnv)) {
    delete env.CLAUDE_CODE_NO_FLICKER;
  }
  return env;
}

// 新版 Claude Code(v2.1.89+)默认全屏渲染(整屏原地重绘)→ 嵌入式 xterm 攒不出 scrollback、
// 终端只剩一屏、上滚不到历史(claude 自身行为，cc-viewer 剥离 NO_FLICKER 也无济于事)。
// cc-viewer 默认向 claude 注入官方开关 CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1，使其回到经典
// 流式渲染、终端恢复可滚历史(与默认剥离 NO_FLICKER 同款取舍:保 scrollback)。想保留全屏无闪烁
// 渲染的用户 opt-out:设 CCV_KEEP_CLAUDE_FULLSCREEN=1；亦尊重用户显式 export 的
// CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN(含显式 '0' 主动开全屏)。
export const KEEP_CLAUDE_FULLSCREEN_ENV = 'CCV_KEEP_CLAUDE_FULLSCREEN';

export function applyClaudeAltScreenPref(env, sourceEnv = process.env) {
  if (!env) return env;
  const keepFullscreen = env[KEEP_CLAUDE_FULLSCREEN_ENV] === '1' || sourceEnv?.[KEEP_CLAUDE_FULLSCREEN_ENV] === '1';
  if (!keepFullscreen && env.CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN == null) {
    env.CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN = '1';
  }
  // 不把 cc-viewer 内部开关泄漏给子进程(对齐 _spawnClaudeImpl 对 CCV_ 短路开关的剥离)。
  delete env[KEEP_CLAUDE_FULLSCREEN_ENV];
  return env;
}

function ensureWrapperFile(dir, fileName, content) {
  mkdirSync(dir, { recursive: true });
  const file = join(dir, fileName);
  writeFileSync(file, content, { mode: 0o600 });
  return file;
}

function defaultRcDir() {
  return join(getClaudeConfigDir(), 'cc-viewer', 'shell-rc');
}

/**
 * Prepare an interactive shell for cc-viewer's embedded terminals.
 *
 * Deleting CLAUDE_CODE_NO_FLICKER from the spawned env is enough for direct
 * Claude spawns, but not for scratch/fallback shells: users often export the
 * variable from ~/.zshrc or ~/.bashrc, so the shell would recreate it before
 * they type `claude`. For those shells we install a tiny rc wrapper that loads
 * the user's normal rc file and then unsets the variable again.
 */
export function prepareEmbeddedShellSpawn(shell, env, options = {}) {
  const sourceEnv = options.sourceEnv || process.env;
  const keep = shouldKeepClaudeNoFlicker(env, sourceEnv);
  stripClaudeNoFlickerUnlessOptedIn(env, sourceEnv);
  if (keep) return { command: shell, args: [], env };

  const shellBase = basename(shell);
  const homeDir = options.homeDir || homedir();
  const rcDir = options.rcDir || defaultRcDir();

  if (shellBase === 'zsh') {
    const zshEnvWrapper = [
      '# Generated by cc-viewer. Do not edit.',
      '__ccv_wrapper_zdotdir="${ZDOTDIR:-$HOME}"',
      '__ccv_original_zdotdir="${CCV_ORIGINAL_ZDOTDIR:-$HOME}"',
      'if [[ "$__ccv_original_zdotdir" != "$__ccv_wrapper_zdotdir" && -r "$__ccv_original_zdotdir/.zshenv" ]]; then',
      '  source "$__ccv_original_zdotdir/.zshenv"',
      'fi',
      '# ZDOTDIR was set to the wrapper dir by prepareEmbeddedShellSpawn before zsh',
      "# started, so the previous form `${ZDOTDIR:-$__ccv_original_zdotdir}` always",
      "# selected the wrapper dir; the later .zshrc then compared wrapper==wrapper",
      "# and silently skipped sourcing the user's real ~/.zshrc. Compare against",
      '# __ccv_wrapper_zdotdir instead: only treat the current ZDOTDIR as',
      "# user-overridden when the user's .zshenv (sourced above) actually changed it.",
      'if [[ "$ZDOTDIR" != "$__ccv_wrapper_zdotdir" ]]; then',
      '  export CCV_EFFECTIVE_ZDOTDIR="$ZDOTDIR"',
      'else',
      '  export CCV_EFFECTIVE_ZDOTDIR="$__ccv_original_zdotdir"',
      'fi',
      'export ZDOTDIR="$__ccv_wrapper_zdotdir"',
      'unset __ccv_original_zdotdir __ccv_wrapper_zdotdir',
      '',
    ].join('\n');
    const zshRcWrapper = [
      '# Generated by cc-viewer. Do not edit.',
      '__ccv_wrapper_zdotdir="$ZDOTDIR"',
      '__ccv_original_zdotdir="${CCV_EFFECTIVE_ZDOTDIR:-${CCV_ORIGINAL_ZDOTDIR:-$HOME}}"',
      'if [[ "$__ccv_original_zdotdir" != "$__ccv_wrapper_zdotdir" && -r "$__ccv_original_zdotdir/.zshrc" ]]; then',
      '  ZDOTDIR="$__ccv_original_zdotdir"',
      '  source "$__ccv_original_zdotdir/.zshrc"',
      '  export ZDOTDIR="$__ccv_wrapper_zdotdir"',
      'fi',
      'unset CLAUDE_CODE_NO_FLICKER',
      'unset CCV_EFFECTIVE_ZDOTDIR',
      'unset __ccv_original_zdotdir __ccv_wrapper_zdotdir',
      '',
    ].join('\n');
    ensureWrapperFile(rcDir, '.zshenv', zshEnvWrapper);
    ensureWrapperFile(rcDir, '.zshrc', zshRcWrapper);
    env.CCV_ORIGINAL_ZDOTDIR = env.ZDOTDIR || homeDir;
    env.ZDOTDIR = rcDir;
    return { command: shell, args: [], env };
  }

  if (shellBase === 'bash') {
    const wrapper = [
      '# Generated by cc-viewer. Do not edit.',
      'if [ -r "${CCV_ORIGINAL_BASHRC:-$HOME/.bashrc}" ]; then',
      '  . "${CCV_ORIGINAL_BASHRC:-$HOME/.bashrc}"',
      'fi',
      'unset CLAUDE_CODE_NO_FLICKER',
      '',
    ].join('\n');
    const rcFile = ensureWrapperFile(rcDir, 'bashrc', wrapper);
    env.CCV_ORIGINAL_BASHRC = env.CCV_ORIGINAL_BASHRC || join(homeDir, '.bashrc');
    return { command: shell, args: ['--rcfile', rcFile, '-i'], env };
  }

  if (shellBase === 'fish') {
    return { command: shell, args: ['--init-command', 'set -e CLAUDE_CODE_NO_FLICKER'], env };
  }

  return { command: shell, args: [], env };
}
