// 数据安全:本套件只在 mkdtemp 临时目录里读写,绝不触碰真实 CCV_LOG_DIR。
import { describe, it, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  extractUserTexts, isSystemText, flattenPromptText, sortEpochFiles,
  collectPromptsFromEvents, readPromptsHead,
} from '../server/lib/user-prompt-extract.js';

const tmpDir = mkdtempSync(join(tmpdir(), 'ccv-upx-'));
after(() => { try { rmSync(tmpDir, { recursive: true, force: true }); } catch {} });

describe('extractUserTexts (shared module)', () => {
  it('strips local-command-caveat / command wrappers and keeps real prompts', () => {
    const msgs = [
      { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>\n<command-name>/theme</command-name>' },
      { role: 'user', content: 'real question about the build' },
    ];
    assert.deepEqual(extractUserTexts(msgs), ['real question about the build']);
  });

  it('skips tool_result-only user turns and non-text blocks', () => {
    const msgs = [
      { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'x', content: 'output' }] },
      { role: 'user', content: [{ type: 'image', source: {} }, { type: 'text', text: 'describe this image' }] },
      { role: 'assistant', content: [{ type: 'text', text: 'not a user turn' }] },
    ];
    assert.deepEqual(extractUserTexts(msgs), ['describe this image']);
  });

  it('drops CLI-synthesized prompts (Recap/Title/Compact/Topic/Summary — contentFilter parity)', () => {
    const msgs = [
      { role: 'user', content: 'The user stepped away and is coming back. Recap in under 40 words what was done.' },
      { role: 'user', content: 'Please write a short title for this conversation.' },
      { role: 'user', content: 'This session is being continued from a previous conversation that ran out of context.' },
      { role: 'user', content: 'quoting: The user stepped away — but this is MY text' }, // ^-anchored: not swallowed
    ];
    assert.deepEqual(extractUserTexts(msgs), ['quoting: The user stepped away — but this is MY text']);
  });

  it('drops SUGGESTION MODE and system-reminder texts', () => {
    assert.equal(isSystemText('[SUGGESTION MODE: predict the next input]'), true);
    assert.equal(isSystemText('<system-reminder>bg noise</system-reminder>'), true);
    const msgs = [{ role: 'user', content: [{ type: 'text', text: '[SUGGESTION MODE: x]' }] }];
    assert.deepEqual(extractUserTexts(msgs), []);
  });
});

describe('flattenPromptText / sortEpochFiles', () => {
  it('normalizes newlines and caps at 100 chars', () => {
    const flat = flattenPromptText('line1\nline2\r\n' + 'x'.repeat(200));
    assert.ok(!flat.includes('\n'));
    assert.equal(flat.length, 100);
  });

  it('sorts epoch files numerically (e2 < e10) and drops non-epoch names', () => {
    assert.deepEqual(
      sortEpochFiles(['e10.jsonl', 'e2.jsonl', 'e0.jsonl', 'prompts.jsonl', 'notes.txt']),
      ['e0.jsonl', 'e2.jsonl', 'e10.jsonl'],
    );
  });
});

describe('collectPromptsFromEvents', () => {
  it('dedupes across snapshot replays, guards ctl lines, skips suggestion events', () => {
    const events = [
      { seq: 1, t: 'snapshot', msgs: [{ role: 'user', content: 'q1' }] },
      { seq: 2, t: 'append', msgs: [{ role: 'assistant', content: 'a1' }, { role: 'user', content: 'q2' }] },
      // process-restart snapshot replays the full history — must not duplicate
      { seq: 3, t: 'snapshot', msgs: [{ role: 'user', content: 'q1' }, { role: 'user', content: 'q2' }] },
      // replace-tail carries the swapped tail as .msg — e.g. a suggestion
      // probe replaced by the user's REAL next prompt; must be collected.
      { seq: 4, t: 'ctl', op: 'replace-tail', msg: { role: 'user', content: 'real prompt after probe' } },
      { seq: 5, t: 'ctl', op: 'compact' }, // no msg — ignored
      { seq: 6, t: 'append', msgs: [{ role: 'user', content: [{ type: 'text', text: '[SUGGESTION MODE: y]' }] }] },
    ];
    const acc = {};
    collectPromptsFromEvents(events, acc);
    assert.deepEqual(acc.out, ['q1', 'q2', 'real prompt after probe']);
    // accumulator carries across epoch files
    collectPromptsFromEvents([{ seq: 7, msgs: [{ role: 'user', content: 'q3' }] }], acc);
    assert.deepEqual(acc.out, ['q1', 'q2', 'real prompt after probe', 'q3']);
  });
});

describe('readPromptsHead', () => {
  it('reads {seq,texts} lines, dedupes, tolerates corrupt lines, missing file → []', () => {
    const p = join(tmpDir, 'prompts.jsonl');
    writeFileSync(p, [
      JSON.stringify({ seq: 1, texts: ['q1', 'q2'] }),
      'not json at all',
      JSON.stringify({ seq: 2, texts: ['q2', 'q3'] }),
      JSON.stringify({ seq: 3, nope: true }),
    ].join('\n') + '\n');
    assert.deepEqual(readPromptsHead(p), ['q1', 'q2', 'q3']);
    assert.deepEqual(readPromptsHead(join(tmpDir, 'absent.jsonl')), []);
  });

  it('stays bounded: content beyond maxBytes (incl. a torn tail line) is dropped', () => {
    const p = join(tmpDir, 'prompts-big.jsonl');
    const line1 = JSON.stringify({ seq: 1, texts: ['head-prompt'] }) + '\n';
    const line2 = JSON.stringify({ seq: 2, texts: ['tail-prompt-'.repeat(50)] }) + '\n';
    writeFileSync(p, line1 + line2);
    const out = readPromptsHead(p, line1.length + 10); // budget cuts into line2
    assert.deepEqual(out, ['head-prompt'], 'torn tail line dropped, head intact');
  });
});
